メールアドレスを変更した際に表示される内容を変更 #74
SofPyon/inaka-portal pull request #103
Opened 2019-12-16 14:24 UTC by hosakou

- 「まだ登録は完了していません！」を表示しないように変更

Close #74

2019-12-16 14:42 UTC, SofPyon requested changes
@hosakou 

修正ありがとう！
１点確認をお願いします！

あとごめん！issue に書き忘れてたんだけど、確認メールの方、ユーザー登録用の文面になってしまってるので、名前以外の文面、以下に変更してもらえないでしょうか？

```
ユーザー情報の変更手続きを完了するには、以下のボタンをクリックしてください。
```

-----

![image](https://user-images.githubusercontent.com/6687653/70915526-56e33680-205d-11ea-882e-af772e380beb.png)

2019-12-16 14:42 UTC, SofPyon commented on resources/views/auth/verify.blade.php
> +            @endif
学籍番号・メールアドレスの変更の場合は、「まだユーザー情報の変更は完了していません！」と表示したいです！

2019-12-17 06:02 UTC, hosakou commented
まだ 「メッセージを再送する」ボタンから送信すると「登録完了のメール」が送信されてしまいます

2019-12-17 08:52 UTC, SofPyon requested changes
@hosakou 

修正ありがとう！

> まだ 「メッセージを再送する」ボタンから送信すると「登録完了のメール」が送信されてしまいます

`resources/views/auth/verify.blade.php` というファイルに再送ボタンがあるんだけど、ここのフォームで、ユーザー登録ではなくユーザー情報編集しただけだよ！という情報を一緒に送るのはどうでしょうか？

```html
<input type="hidden" name="is_edit" value="true">
```

2019-12-17 08:52 UTC, SofPyon commented on app/Mail/Auth/EditEmailVerificationMailable.php
> +class EditEmailVerificationMailable extends Mailable
EmailVerificationMailable とは別に新しく Mailable 作る必要はないかと！

コンストラクタ(26行目)の第三引数で $type を受け取り、 $type に応じて送信するメールの文面を変化させれば良いのでは？

2019-12-17 08:52 UTC, SofPyon commented on app/Mail/Auth/EditEmailVerificationMailable.php
> +    public $userName;
補足）

Laravel の Mailable クラスでは public プロパティで変数をビューに渡します。
（with も使える）

つまり、ここの $userName という変数は Blade 側でも使えるということです。

https://readouble.com/laravel/5.8/ja/mail.html#view-data

---

このことを活用して、Blade に $type をわたし、Blade 側で送る文面を条件分岐した方が良い気がします！

2019-12-17 08:52 UTC, SofPyon commented on app/Services/Auth/EmailService.php
> +    public function sendAll(User $user, $type = 'register')
これだと、 `register` の他に `edit` という引数も受け取れるということがわかりづらいですね。

$is_edit とかで良いのでは？
false ならユーザー登録時で、true ならユーザー編集時みたいな感じ

2019-12-17 08:52 UTC, SofPyon commented on resources/views/emails/auth/editverify.blade.php
> +
補足）
この Blade ファイルにインデントを入れてしまうと、表示が崩れてしまうため、

このファイルにはインデントが一切入っていません。

（このファイルの内容は Markdown として扱われる）

2019-12-17 09:05 UTC, SofPyon commented
@hosakou 

あ、ごめん！！！

メール認証が完了した後に出てくる画面、「ユーザー登録が完了しました」になってた……

これも修正をお願いしたいです！

修正箇所を整理できていなくてごめん！

![image](https://user-images.githubusercontent.com/6687653/70980984-a70ed700-20f7-11ea-985a-33542090ca60.png)

2019-12-20 11:19 UTC, SofPyon requested changes
@hosakou

修正ありがとう！

users テーブルに、ユーザー登録が完了したかどうかを示すフラグを追加する方針、良いと思います！

動作確認できてないですが、何点か確認お願いしたいです！

2019-12-20 11:19 UTC, SofPyon commented on resources/views/auth/logout.blade.php
> +    {{ dd(Auth::user())}}
消し忘れ？

2019-12-20 11:19 UTC, SofPyon commented on app/Mail/Auth/EmailVerificationMailable.php
> +        $this->is_edit = $is_edit;
メモ) 他の変数名は `camelCase` になっていて、ここだけ `snake_case` なのは不自然なので、ここは `$isEdit` にした方が良かったかも……

2019-12-20 11:19 UTC, SofPyon commented on database/migrations/2019_12_19_220254_add_is_verified_to_users.php
> +            $table->boolean('is_verified')->default(false)->after('univemail_verified_at');
`verify` は、他のところだと「メール認証が完了している」的な意味で使ってますが、今回の場合( `is_verified`) だと「ユーザー登録が完了している」的な意味になっており、紛らわしいです、、

**変数名や関数名は、わかりやすく正確な命名を心がけてください！！**

今回だったら is_signed_up とかかな？

2019-12-20 11:19 UTC, SofPyon commented on resources/views/emails/auth/verify.blade.php
> +「{{ config('app.name') }}」{{ $is_edit ? 'にて、ユーザー情報が変更されました。' : 'にご登録いただき、ありがとうございます。' }}
この条件分岐の仕方は、ちょっとわかりづらいかな…

(app.name と「にて」以降の文が途切れてしまっている)

愚直に、こう書いてもよいかも

```blade
@if ( /* ... */ )
「{{ config('app.name') }}」にて、ユーザー情報の〜
@else
「{{ config('app.name') }}」にご登録いただき、ありがとうございます。
@endif
```

2019-12-20 11:19 UTC, SofPyon commented on app/Http/Controllers/Users/EditInfoAction.php
> +        $user->setVerified();
setVerified って、「ユーザー登録が完了したと記録する」的な意味の関数だと思うので、ユーザー編集画面にこの関数を実行するのは、タイミング的に不自然では？

確かに、もう既に登録してくれてるユーザーが verified にならない問題はあるけどね…

実行するなら、ユーザー登録のメール認証が完了したタイミングかな

2019-12-20 11:19 UTC, SofPyon commented on app/Eloquents/User.php
> +        if ($this->areBothEmailsVerified()) {
関数名では「setVerified」となっているので、この関数を使う人は、どんな事情があっても is_verified が true になることを期待します

ところが、現状は areBothEmailsVerified が true でないと is_verified が true にセットされず、関数名と合っていないですね

例えば、「メール認証が完了していなくても、ユーザー登録が完了したとスタッフが設定できるようにする」機能を開発する時に不便です

なので、こちら条件分岐は無しでお願いします！

2020-01-03 14:52 UTC, SofPyon approved these changes
@hosakou 
ありがとう！
これでマージします！ 🎉

2020-01-03 14:52 UTC, SofPyon commented on app/Http/Middleware/EnsureEmailIsVerified.php
> +        $user->setSignedUp();
アクセスされるたびに SQL の update 文が実行されることになるので、ちょっと微妙な気もするけど、今回は OK にします

2020-01-03 14:52 UTC, SofPyon commented on resources/views/auth/verify_completed.blade.php
> +                <strong>手続きが完了しました！</strong>
せっかく条件分岐のコード書いてくれたんだけど、確認してみたところ、ユーザー登録の場合も「ユーザー情報の変更が完了されました」と表示されてしまっていました……

is_signed_up が true になった後に表示される画面なので、よくよく考えたら当たり前だったんだけど、ここを実装し直すのも面倒なので、とりあえず、ユーザー登録・情報変更のどちらでも、問題なさそうな文言にしてみました

2020-01-03 14:53 UTC, merged