【デザインリニューアル】申請（一覧画面篇）#168
SofPyon/inaka-portal pull request #180
Opened 2020-01-08 13:34 UTC by hosakou

## 実装内容
close #168 

- スケジュールページを参考に作成しました
- 2団体以上に所属している場合
  - 以前作成したセレクターへ転送
  - GETパラメーターの `circle` にサークルのIDを取ります
- Codeigniter でも `/forms` が使われていたので `/applications` に変更しました

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2020-01-08 16:07 UTC, SofPyon reviewed
@hosakou 

実装ありがとう！
コードはあとでじっくり読んでみます！

一点、issue の方に書き忘れていた僕が悪いんだけど、団体に所属していない場合の処理が別途必要です！

<img width="1679" alt="Whoops__There_was_an_error_" src="https://user-images.githubusercontent.com/6687653/71994470-223d5600-327c-11ea-8e01-7cd7a6b442cd.png">

なので、以下について追加で実装してくれると嬉しいです！

- 団体に所属していない状態でアクセスすると、「申請を行うには、団体参加登録が必要です」と表示される
    - エラー画面のイメージとしては、「退会」画面のエラー表示と同じような感じでお願いします

2020-01-08 16:52 UTC, hosakou commented
団体に所属していないときのことを忘れていました！
修正したのでお願いします

2020-01-11 03:30 UTC, SofPyon commented
テスト期間なのでレビューは2月以降にやります！

2020-01-30 00:48 UTC, SofPyon requested changes
@hosakou 
テスト期間終わったので、レビューします！

数多いですが、確認お願いします！！

2020-01-30 00:48 UTC, SofPyon commented on app/Eloquents/Form.php
> +    public function scopeNowClosed($query)
imo 
`scopeClosed` の方がシンプルで良さそう

2020-01-30 00:48 UTC, SofPyon commented on app/Eloquents/Form.php
> +    public function scopeNowOpend($query)
typo?

`scopeOpen` の方がシンプルで良さそう

2020-01-30 00:48 UTC, SofPyon commented on app/Eloquents/Form.php
> +    public function scopeIsPublic($query)
imho

公開中のものを取得するというニュアンスで `is public` という疑問形なのはちょっと変なので `scopePublic` の方が良さそう

2020-01-30 00:48 UTC, SofPyon commented on app/Http/Controllers/Circles/Selector/ShowAction.php
> +        $redirect = request('redirect');
この修正の意図は…？

今まで基本的にリクエストは引数で受け取ってきたというのと、今後 FormRequest クラスを利用する可能性を考えると、リクエストは引数から受け取りたいです！

-----

Why use dependency injection for Request object vs request() helper in Laravel?
https://stackoverflow.com/questions/52470867/why-use-dependency-injection-for-request-object-vs-request-helper-in-laravel

↑書き方の違いであって、動作などに違いがあるわけではないですが…

2020-01-30 00:48 UTC, SofPyon commented on app/Http/Controllers/Forms/AllAction.php
> +                $circle = $circles[0];
現状、団体数が 1 つの場合、 `?circle=` の値が無視されるようですが、この挙動は微妙かな…

所属団体数が 1 つしかない場合は `?circle=(団体ID)` がつくページへリダイレクトと言う形にして欲しいです。また、`?circle=` の後に続く団体に所属していない場合は、団体セレクタへリダイレクトしてほしいです

（無限リダイレクトに注意）

2020-01-30 00:48 UTC, SofPyon commented on app/Http/Controllers/Forms/AllAction.php
> +        } else {
if の次の `{}` の中身が空なので、この書き方は冗長ですね

`if (empty($circle) || Gate::denies('circle.belongsTo', $circle))` という書き方はどうでしょう？

2020-01-30 00:48 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +        <p><a href="{{ url('/') }}" class="btn is-primary is-block" role="button">ホームに戻る</a></p>
これは普通にリンクなので `role="button"` は不要かと

2020-01-30 00:48 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +                手続きが完了していません
「手続きが完了していません」だと曖昧なので、「団体参加登録が未完了」的な感じにしたいです

2020-01-30 00:48 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +                    @if($form->open_at > $now)
answered はメソッドにしてくれたし、せっかくだからこれ（フォームが受付期間中かどうか）もメソッドにしよう

2020-01-30 00:48 UTC, SofPyon commented on app/Http/Controllers/Forms/AllAction.php
> +        $forms = Form::IsPublic()->CloseOrder()->get();
スコープメソッドも先頭の文字は小文字でお願いします！

（isPublic を public に改名する場合、 Form::public() かな）

```suggestion
        $forms = Form::isPublic()->closeOrder()->get();
```

2020-01-30 00:48 UTC, SofPyon commented on resources/sass/v2/modules/_badge.scss
> +        color: white;
色名での指定は基本ナシでお願いします！

```suggestion
        color: #fff;
```

2020-01-30 00:48 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +                        <small><span class="badge is-success">提出済</span></small>
imho

```suggestion
                        <small class="badge is-success">提出済</small>
```

2020-01-30 00:48 UTC, SofPyon commented on application/config/routes.php
> +$route["applications/(:num)/answers/create"] = "home/Applications_form/index/$1/create";
メモ）

#183 が完了したら、forms に戻します！

2020-01-30 00:48 UTC, SofPyon commented on resources/views/v2/includes/drawer.blade.php
> +            <a href="{{ route('forms.index') }}" class="drawer-nav__link">
リンク先の変更ありがとう！

下タブの申請リンクも修正必要かも

![FD8E606F-E16F-4596-97EE-1EB72ED8A1C0](https://user-images.githubusercontent.com/6687653/72891737-44dd6d80-3d58-11ea-9463-033d94b0f353.jpeg)

2020-01-30 00:48 UTC, SofPyon commented on app/Http/Controllers/Forms/AllAction.php
> +            ->with('now', new CarbonImmutable());
```suggestion
            ->with('now', new CarbonImmutable());
            ->with('now', now());
```

2020-02-08 06:36 UTC, SofPyon approved these changes
@hosakou 

修正ありがとう！

これで、ドロワーから行けるページ、全部 Project v2 対応！！

2020-02-08 06:38 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +<list-view>
list-view を app-container で囲むのはこちらでやっておきます！

2020-02-08 06:38 UTC, SofPyon commented on resources/views/v2/forms/list.blade.php
> +    <list-view-item href="/applications/{{ $form->id }}/answers/create?circle_id={{ $circle->id }}">
Project v2 じゃないページにリンクはるときは `data-turbolinks="false"` が必要です！
これもこっちで修正しておきます！

これがないとリンク先でレイアウト崩れちゃう……

![image](https://user-images.githubusercontent.com/6687653/74080607-0995ab00-4a89-11ea-9bff-ed9574cb2b13.png)

2020-02-08 06:39 UTC, SofPyon commented
正規表現で Laravel と CodeIgniter を振り分けられるようになり次第、マージしますね

2020-02-12 05:50 UTC, SofPyon commented
@hosakou 
こちらのプルリクエストですが、現在僕の方で開発を行っている申請フォームの方と同時にリリースしたいので、master ではなく fix169 (#169) の方へマージすることにしました！

2020-02-12 05:56 UTC, merged