【Staff/申請】同じ選択肢を登録できないようにする #216
SofPyon/inaka-portal pull request #221
Opened 2020-02-12 13:13 UTC by hosakou

## 実装内容
close #216 

- `textarea` からフォーカスが外れたときに重複を削除
- 入力時も重複している項目を表示しないように
- DBに保存する際に重複を削除して保存

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2020-02-12 15:04 UTC, SofPyon requested changes
@hosakou 

実装ありがとう！

動作確認してみたところ、選択肢を変更しても、変更が保存されないようです…！
ご確認ください！

2020-02-12 15:04 UTC, SofPyon commented on resources/js/forms_editor/components/form/QuestionRadio.vue
> +          <input class="form-check-input" type="radio" tabindex="-1" />
前々から気になってました！
修正ありがとう！！！

2020-02-12 15:04 UTC, SofPyon commented on app/Services/Forms/QuestionsService.php
>          // TODO: CodeIgniter を廃止したら、以下の処理は削除する
```php
// CodeIgniter 側の in_list バリデーションルールを使いたいが、
// CodeIgniter ではバリデーションルールを単なる文字列で表す。
// そのため、CodeIgniter のバリデーションの邪魔になる文字列は
// 削除する
// TODO: CodeIgniter を廃止したら、以下の処理は削除する
```

コメントの位置がここだと、CodeIgniter が廃止された際、重複した選択肢を削除する処理も一緒に消してしまいそうで怖いので、コメントを書き換えて欲しいです

```suggestion
        // TODO: CodeIgniter を廃止したら、str_replace をする処理は削除する
```

とかかな

2020-02-12 15:04 UTC, SofPyon commented on resources/js/forms_editor/components/form/EditPanel.vue
> +          "
この書き方だと、正常に動作しないっぽい…？

こうすると良いかも↓

```vue
<textarea
    class="form-control"
    v-model="options"
    @blur="onBlur"
>
```

```js
methods: {
    onBlur() {
        this.deleteDuplication();
        this.save();
    },
    save() {
        // 省略
    },
    deleteDuplication() {
        // 省略
    },
    // 省略
}
```

2020-02-12 15:04 UTC, SofPyon commented on resources/js/forms_editor/components/form/EditPanel.vue
> +        const options = new Set(this.options.trim().split(/\r\n|\n/))
なるほど、Set 使う手があったか…！

2020-02-12 15:24 UTC, hosakou commented on resources/js/forms_editor/components/form/EditPanel.vue
> +          "
セミコロンで区切ってたんですがそうなってしまったみたいです！！

修正しておきます！

2020-02-13 00:16 UTC, SofPyon requested changes
@hosakou 
修正ありがとう！
動作確認しましたが、問題なさそうです

最後、一点だけ修正お願いします！
前回の指摘漏れです、ごめん！

2020-02-13 00:16 UTC, SofPyon commented on resources/js/forms_editor/components/form/EditPanel.vue
> +        const options = new Set(this.options.trim().split(/\r\n|\n/))
PHP 側では array_map で trim する処理を入れてくれたので、JavaScript 側でも配列の各要素を trim する処理を入れて欲しいです！

たぶん、this.options を trim する代わりに、split でできた配列を map で trim する感じかな…？

2020-02-13 14:05 UTC, SofPyon commented
メモ）
IE で起動したら、「IE 非対応」と表示する

2020-02-21 12:43 UTC, SofPyon reviewed
@hosakou 
修正ありがとう！

IE で表示された時「IE には対応していません」っていうエラーを出す実装してくれたけど、Promise のポリフィルを入れても IE だと動かなかった？？

2020-02-21 13:09 UTC, hosakou commented
@SofPyon 
IE だとエラーがでてしまうみたいです。

![image](https://user-images.githubusercontent.com/8391342/75036789-fad1de00-54f5-11ea-97b1-37fe69532bf9.png)

2020-02-21 13:46 UTC, SofPyon commented
@hosakou 
なるほど…

さっきコミットした https://github.com/SofPyon/inaka-portal/pull/221/commits/083efa19ef9f09854953db96de174270027aa9ee で、Promise 以外のポリフィルが入るようにしてみたんだけど、これは動きそう…？

2020-02-21 14:16 UTC, hosakou commented
@SofPyon 
動作しました！！設問の変更等も問題なく動いてます！

2020-02-21 14:19 UTC, SofPyon requested changes
@hosakou 

確認ありがとう！
よかった！

ということで、せっかく実装してくれたんだけど、IE 非対応表示は削除しましょう！

あと、コンフリクトしてるので解消お願いします！

![image](https://user-images.githubusercontent.com/6687653/75041839-b730a180-5500-11ea-853e-b91232880abd.png)

2020-02-21 14:36 UTC, hosakou commented
@SofPyon 
修正できました！！

2020-02-21 14:56 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！

2020-02-21 14:56 UTC, SofPyon commented on resources/js/v2/components/Forms/QuestionCheckbox.vue
> +        :checked="Array.isArray(value) && value.indexOf(option) >= 0"
ポリフィル入れたから、 `includes` に戻してもよかったかも
今回はこのままでOKです！

2020-02-21 14:56 UTC, merged