【ListView(スマホ)】空の状態の時の表示no #219
SofPyon/inaka-portal pull request #222
Opened 2020-02-12 16:47 UTC by hosakou

## 実装内容
close #

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2020-02-13 00:27 UTC, SofPyon requested changes
@hosakou 
ありがとう！

> pages と documents で空の場合でも empty が false を返していたため修正

そうだったんだ…知らなかった！

一点、修正お願いします！

2020-02-13 00:27 UTC, SofPyon commented on app/Http/Controllers/HomeAction.php
> +
なるほど！
中身が空でも empty は false になっちゃうんだね…

ただ、この書き方を今後全ページでやっていくのはダルいので、もうちょっとシンプルにしたいです…！

Action 側は今までと同じような方法でデータを取得するとして、View 側を、以下のように修正して欲しいです！

```blade
@if ($documents->isEmpty())
```

（Document::get() などが返す値は、配列ではなくコレクションと呼ばれる Laravel 独自のオブジェクトです）

https://www.larajapan.com/2019/03/02/isempty%E3%81%A7%E3%81%97%E3%81%9F/

2020-02-14 13:26 UTC, SofPyon requested changes
@hosakou 
修正ありがとう！
こちら確認お願いします！

2020-02-14 13:26 UTC, SofPyon commented on app/Eloquents/Document.php
> +        return count($this) === 0;
いや、isEmpty はコレクションというクラスが持っているメソッドなので、こちら実装不要です！

そもそも Document クラスは Eloquent なのでこのメソッドは呼ばれません！イメージとしては、コレクションの中に Eloquent がたくさん入っている感じです

https://readouble.com/laravel/5.8/ja/collections.html#method-isempty

![image](https://user-images.githubusercontent.com/6687653/74535044-60fbb580-4f78-11ea-8c1c-60fe8cc5ae49.png)

2020-02-14 13:26 UTC, SofPyon commented on resources/views/v2/schedules/list.blade.php
>      @empty ($schedules)
修正もれ？
ここも $schedules->isEmpty() 使った方が良さそう？

2020-02-14 16:29 UTC, hosakou commented on app/Eloquents/Document.php
> +        return count($this) === 0;
そうだったんですね！了解です！！

2020-02-14 16:38 UTC, hosakou commented on resources/views/v2/schedules/list.blade.php
>      @empty ($schedules)
スケジュールは `gropuByMonth` で配列になっていたのでこのままで大丈夫でした！

2020-02-14 16:56 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！
（トップページ対応漏れていたので、こちらで修正しておきました https://github.com/SofPyon/inaka-portal/pull/222/commits/c965e76b2f7491963b77f84f6209916f71f4447d ）

2020-02-14 16:58 UTC, merged