【デザインリニューアル】申請（フォーム篇） #169
SofPyon/inaka-portal pull request #228
Opened 2020-02-14 16:40 UTC by SofPyon

## 実装内容
close #169

申請の回答ページを v2 にした

## レビュワーに見て欲しい点
- 全設問、ちゃんと回答できるか
- 団体あたり回答数制限機能が機能するか
- 必須項目がちゃんと必須か・そのほか各種フォーム設定や申請フォームエディターでの編集内容が適切にフォームに反映されているか
- メールがちゃんと届くか
- ファイルアップロードがちゃんと動作するか
- アップロードしたファイルをスタッフモードからダウンロードすることができるか
- など、**念入りにチェックしてもらえると嬉しいです**

## 参考URL

2020-02-16 08:42 UTC, hosakou requested changes
レビュー遅くなりました！

まだ確認漏れがあるかもしれませんがとりあえず修正したほうが良さそうなところがいくつかあったのでお願いします！

2020-02-16 08:42 UTC, hosakou commented on app/Http/Requests/Forms/BaseAnswerRequest.php
> +        }, $all['answers']);
解答欄を削除して送信したり、設問がないフォームを送信すると `$all['answers']` に `null` が渡されてエラーになるみたいです！

2020-02-16 08:42 UTC, hosakou commented on resources/js/v2/components/Forms/QuestionHeading.vue
> +  </ListViewBaseItem>
最下部に セクション見出し があるときにぎゅうぎゅうな感じなので下に余裕がほしいです！

![image](https://user-images.githubusercontent.com/8391342/74600751-265d5e80-50d9-11ea-8a97-e85283ff79e3.png)

2020-02-16 08:42 UTC, hosakou commented on app/Http/Controllers/Forms/Answers/EditAction.php
> +    {
「団体A」が「フォーム1」で「回答ID 1」を作成済みの場合に
「団体A」が `/forms__v2/5/answers/1/edit` など、URLを存在する フォームID に書き換えると 回答ID と紐付いていないフォームが表示されます！

2020-02-16 08:42 UTC, hosakou commented on resources/sass/v2/modules/_badge.scss
> +        color: white;
前回指摘されていたのに修正し忘れていました！
修正しておきます！！

2020-02-16 10:21 UTC, SofPyon commented
@hosakou 

レビューありがとう！
指摘してくれた部分については修正したのでご確認ください！

-----

↓ぎゅうぎゅうだった件はこのように修正しました

![image](https://user-images.githubusercontent.com/6687653/74602824-3b91b780-50f0-11ea-8b92-9bec94ea8320.png)

2020-02-17 13:06 UTC, hosakou approved these changes
ぎゅうぎゅうなどの修正ありがとうございます！！
ほかも問題なく動いています！

IE だと 設問が表示されないのですが、[ここ](https://github.com/SofPyon/inaka-portal/pull/221#issuecomment-585769730)で僕がやってみても大丈夫ですか？

2020-02-17 13:43 UTC, SofPyon commented
@hosakou 
確認ありがとう！
マージします！

> IE だと 設問が表示されないのですが、ここで僕がやってみても大丈夫ですか？

マジか…

とりあえず IE でも動くようにできないか 1 時間くらい試してもらって、ダメだったら「IE 非対応」と表示する対応してもらっても良いでしょうか？

2020-02-17 13:43 UTC, merged