【エラー画面】ページデザインを他のページと統一する #187
SofPyon/inaka-portal pull request #277
Opened 2020-03-03 12:07 UTC by hosakou

## 実装内容
close #187 

- エラー画面のデザインを変更
  - v2のドロワーなどを表示するように(503以外)
- 500 503 のみ Twitter を表示するようにしてみました
  - `.env` の `PORTAL_ADMIN_TWITTER` に Twitterスクリーンネームの `@` 以下を指定すると表示されます

## 懸念点

## レビュワーに見て欲しい点
- デザイン的にどうなのか

## 参考URL

2020-03-03 14:52 UTC, SofPyon requested changes
@hosakou 

実装ありがとう！
デザインもいい感じです！！

以下確認をお願いします！

-----

- 「戻る」ボタンが欲しいです。例えばリンク先が間違っているリンクをクリックして 404 が出てきたときなどに、前のページに戻れると便利なので…！

-----

- IT詳しくない人が「503」という数字をみても理解されなさそうな気がします。エラーコードじゃなくて、日本語の方(title)を強調したいです。イメージとしては任天堂の感じかな

<img width="783" alt="スクリーンショット_2020-03-03_23_30_52" src="https://user-images.githubusercontent.com/6687653/75787003-701c9900-5da9-11ea-9ac0-4104db7b9f1d.png">

-----

現状、上下の余白が少し足りない気がします。もうちょっとゆとりを持たせましょう！

<img width="965" alt="Service_Unavailable_—_野田祭_参加団体向けシステム" src="https://user-images.githubusercontent.com/6687653/75787194-b1ad4400-5da9-11ea-904b-785adf7d6ccd.png">

2020-03-03 14:52 UTC, SofPyon commented on resources/views/errors/layout.blade.php
> +@endsection
わざわざ `head` というセクションを作らなくても、 `@push('js')` するだけで対応可能です！
(no_drawer も同様)

```suggestion
@hasSection ('twitter')
@push('js')
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
@endpush
@endif
```

2020-03-03 14:52 UTC, SofPyon commented on resources/views/errors/401.blade.php
>  @section('title', __('Unauthorized'))
タイトルも日本語にしよう！

2020-03-03 14:52 UTC, SofPyon commented on resources/views/errors/419.blade.php
>  @section('message', __('Page Expired'))
この画面(419)、例えばログイン画面を開っぱなしにした後にログインしようとすると出てくるなど、割と頻繁に出てくるので、親切にしたいです…！

title は `ページの有効期限が切れました`、message は `恐れ入りますが、もう一度同じ操作をお試しください` とかかな…？

![image](https://user-images.githubusercontent.com/6687653/75786525-cb01c080-5da8-11ea-9888-f1cfcfc4e1c8.png)

2020-03-03 14:52 UTC, SofPyon commented on resources/sass/v2/layout/_error.scss
> +        max-width: 400px;
```suggestion
        max-width: 400px;
        width: 100%;
```

2020-03-03 14:52 UTC, SofPyon commented on resources/sass/v2/layout/_error.scss
> +        font-size: 300%;
できれば rem 使って欲しい！
```suggestion
        font-size: 3rem;
```

2020-03-03 15:19 UTC, SofPyon commented
あ、ごめん！
wip ついてたのにレビューしちゃった

2020-03-03 15:21 UTC, hosakou commented
@SofPyon 

大丈夫です！
実はアドバイスほしかったのでちょっと期待してました！

2020-03-04 02:33 UTC, SofPyon commented on resources/views/errors/layout.blade.php
> +            <a class="twitter-timeline" data-height="100%" data-chrome="noscrollbar noborders" href="https://twitter.com/{{ config('portal.admin_twitter') }}?ref_src=twsrc%5Etfw">
あ、config('portal.admin_twitter')が未設定の場合、タイムラインは非表示にしたいです！

2020-03-05 13:11 UTC, hosakou commented
@SofPyon 
修正しました！

2020-03-06 14:39 UTC, SofPyon requested changes
@hosakou 
修正ありがとう！
最後、以下の修正お願いしたいです！
修正できたらマージします！

-----

↓ 前回指摘漏れてたんだけど、同じエラー文言が2箇所に出てくるのは微妙なので、ナビバーに出てくるタイトルは別のものにして欲しいです！ `404 Not Found` でも `エラー` でも良いので、文言はお任せします！

![image](https://user-images.githubusercontent.com/6687653/76092756-48c10880-6003-11ea-8e50-793e91d18683.png)

2020-03-06 14:39 UTC, SofPyon commented on resources/views/errors/503.blade.php
> +@section('message', __($exception->getMessage() ?: '時間を開けてもう一度お試しください。'))
メンテナンスモードにするとき `php artisan down --message="メンテナンス中です"` っていうコマンドを使っています。現状、 `message` に指定した文字列が 2 番目に表示されてしまっていて微妙なので、 message の内容はタイトルとして表示できるようにして欲しいです！

![image](https://user-images.githubusercontent.com/6687653/76092063-1bc02600-6002-11ea-9d3c-c1f4e97a6ea6.png)

（あ、「現在」のところ、赤枠で囲い忘れてた……）

2020-03-06 14:39 UTC, SofPyon commented on resources/views/errors/503.blade.php
> +@section('contact', "解決しない場合は「".config('portal.admin_name')."」へお問い合わせください。")
`message` の内容が入力されていても `しばらく経ってから再度お試しください。` は表示して欲しい！

2020-03-07 09:01 UTC, hosakou commented
> 同じエラー文言が2箇所に出てくるのは微妙なので

ぼくもちょっと思ってました！

---
3点修正しました
確認お願いします！

2020-03-07 11:38 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！

2020-03-07 11:38 UTC, merged