【ユーザー登録】is_signed_upをsigned_up_atにする #245
SofPyon/inaka-portal pull request #278
Opened 2020-03-03 14:55 UTC by hosakou

## 実装内容
close #245 

- `is_signed_up` を `signed_up_at` に変更しました。
- メールの認証が完了したときに `signed_up_at` に値をセットするように変更しました。

- `composer migrate` 後に ```UPDATE `users` SET `signed_up_at` = CURRENT_TIMESTAMP WHERE `email_verified_at` IS NOT NULL AND `univemail_verified_at` IS NOT NULL``` の実行をお願いします！

## 懸念点

## レビュワーに見て欲しい点
- 不要な箇所でアップデートが行われないか

## 参考URL

2020-03-03 15:17 UTC, SofPyon requested changes
@hosakou 
修正ありがとう！
動作問題なさそうです。不要な箇所でのアップデートも行われてなさそうです！

以下、1点だけ確認お願いします！

2020-03-03 15:17 UTC, SofPyon commented on app/Services/Auth/EmailService.php
> +        $is_edit = !empty($user->signed_up_at);
せっかくなので、これのゲッター作ろう！

User.php に、こういうメソッド作るとよさそう

```php
public function getIsSignedUpAttribute()
{
    return !empty($user->signed_up_at);
}
```

使い方 : 

```suggestion
        $is_edit = $user->is_signed_up;
```

2020-03-03 15:17 UTC, SofPyon commented on database/factories/UserFactory.php
> +        'signed_up_at' => now(),
修正ありがとう！

2020-03-04 07:43 UTC, hosakou commented on app/Services/Auth/EmailService.php
> +        $is_edit = !empty($user->signed_up_at);
修正しました！

2020-03-05 03:42 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！
マージします

2020-03-05 03:43 UTC, merged

2020-03-05 03:49 UTC, SofPyon commented
本番環境にも

UPDATE `users` SET `signed_up_at` = CURRENT_TIMESTAMP WHERE `email_verified_at` IS NOT NULL AND `univemail_verified_at` IS NOT NULL

流しました！