【Staff/申請】未申請の団体リストを表示できるようにする #197
SofPyon/inaka-portal pull request #279
Opened 2020-03-05 16:09 UTC by hosakou

## 実装内容
close #197 

- 未申請の団体を表示するページを作成しました

## 懸念点
- csvで出力できたら便利かなと思ったのですが一旦保留してます！決して断念しようとしたわけではありません！！
- コントローラーの名前空間は再検討する必要があるかなとおもってます
  - 最初は `Staff\Forms\Submittion\ShowActon` にしようとしてた気がします
- URLが `~~~{form_id}/answers/notans` なので 回答されたものなのかよくわからない感じになっています。
  - 上と同じでもともと `~~~~{form_id}/unsubmitted` にしようとしたのですがそれも長いかなあと。。。

## レビュワーに見て欲しい点

## 参考URL

2020-03-06 15:01 UTC, SofPyon requested changes
@hosakou 
実装ありがとう！
デザインと方向性、特に問題なさそうです！

以下ご確認ください！！

2020-03-06 15:01 UTC, SofPyon commented on app/Http/Controllers/Staff/Forms/Answers/NotAnswered/ShowAction.php
> +        $circles = $this->circle->whereNotIn('id', $submit_circle_ids)->get();
以下の SQL 文だと 1 回 SELECT 実行するだけで未回答団体一覧を取得できそうです！
現状だと 2 回 SELECT が実行されてしまうので、ちょっと微妙かな

```sql
SELECT id, name FROM circles WHERE NOT EXISTS (SELECT circle_id FROM answers WHERE answers.form_id = 【フォームID】 AND answers.circle_id = circles.id)
```

(SQL を実行するときは「SQL インジェクション脆弱性」を生まないように注意！以下のように、プリペアドステートメントを使うようにしてください…！)

```php
// :id のところに 1 が入る
DB::select('select * from users where id = :id', ['id' => 1]);
```

2020-03-06 15:01 UTC, SofPyon commented on routes/web.php
> +                        Route::get('/notans', 'Staff\Forms\Answers\NotAnswered\ShowAction');
> URLが ~~~{form_id}/answers/notans なので 回答されたものなのかよくわからない感じになっています。

URL について確認ありがとう！確かに、「notans…のたんす…？」って感じになってしまいそう…

長くなっちゃうけど、URL は not_answered にしましょう！
理由は、

- 短さよりも分かりやすさを重視したい
- 名前空間と URL の不一致はできるだけ避けたい
    - （URL から名前空間を推測できるようにしたい）

（名前空間については確かに Submittion の方が良いかも。ただ、この PR で修正してしまうとややこしくなってしまいそうなので、今後検討ということにさせてください！）

2020-03-07 11:29 UTC, hosakou commented
@SofPyon 
修正しました！！

2020-03-07 11:40 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！

2020-03-07 11:40 UTC, SofPyon commented on app/Eloquents/Form.php
> +    public function notAnswered()
実装ありがとう！

`$form->notAnswered()` というように、Form Eloquent なのに返り値が Circle っていうところに違和感があるけど、今回はここで大丈夫です！

（書くのであれば `App\Services\AnswersService` あたりに `getNotAnsweredCircles(Form $form)` っていうメソッドを書くのが良さそうかな…。僕も正解分かってない…）

2020-03-07 11:41 UTC, merged