NEWバッジ #258
SofPyon/inaka-portal pull request #287
Opened 2020-03-08 13:12 UTC by hosakou

## 実装内容
close #258 

- 配布資料とお知らせでバッジを表示するようにしました
- CodeIgniter では3日間表示されていたので同じ期間で作成しました

- 共通の処理なので1箇所にまとめて書いたほうが良かったのかなと思っているのですがどうでしょうか

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2020-03-12 14:37 UTC, SofPyon commented
@hosakou 
レビュー遅れて申し訳ない！
インターン中なので週末にできたらレビューします！

2020-03-14 06:24 UTC, SofPyon requested changes
@hosakou 
お待たせしました…！

> 共通の処理なので1箇所にまとめて書いたほうが良かったのかなと思っているのですがどうでしょうか

確かに！現状は以下の処理が２カ所以上に書かれている状況ですね。

- 作成3日以内であればtrueを返す関数
- NEWバッジ

なので、こういう感じにするのが良い気がしますが、いかがでしょうか…？？

--------

## 作成3日以内であればtrueを返す関数
PHP のトレイト機能を使うと良い気がします。

1. `app/Eloquents/Concerns` というフォルダを作成し、 `IsNewTrait.php` というファイルを作成
    - Artisan で Trait を作成する機能はないので手動でファイルを作ってください
    - トレイトは concerns というフォルダに作成するのが慣習らしい…？
1. `IsNewTrait.php` の中身は↓こうする
    - ゲッターじゃなくてただのメソッドにしてみた
    ```php
    <?php
    
    declare(strict_types=1);
    
    namespace App\Eloquents\Concerns;
    
    trait IsNewTrait
    {
        public function isNew()
        {
            if (empty($this->created_at)) {
                throw new \Exception('created_at プロパティがありません');
            }

            $moded_time = $this->created_at->add('3days');
            return $moded_time->gte(now());
        }
    }
    ?>
    ```
1. `isNew` というメソッドを導入したい Model では、以下のようにコードを修正する
    ```php
    <?php
    
    // use なんとか、がいろいろ並んでるところ（省略）
    use App\Eloquents\Concerns\IsNewTrait;    // ←追加
    
    class Document exnteds Model
    {
        use IsNewTrait;    // ←追加
    
        // …（省略）
    }
    ```
1. あとは `$document->isNew()` のように `isNew` メソッドを使えるようになる

## NEWバッジ
そんなにコード量が多くないので、共通化する必要はあまりないかも。

もしやるなら NewBadge.vue っていうコンポーネントを作成し、 `<new-badge />` みたいな使い方をすれば良いと思うけど、わからないな……

2020-03-14 06:24 UTC, SofPyon commented on app/Eloquents/Document.php
> +    public function getIsUpdatedAttribute()
使われていないメソッドは消そう！

2020-03-14 06:24 UTC, SofPyon commented on app/Eloquents/Page.php
> +    public function getIsUpdatedAttribute()
同上

2020-03-14 06:24 UTC, SofPyon commented on app/Eloquents/Document.php
> +        $moded_time = $this->created_at->add('3days');
`$added_time` の間違い？moded の意味調べてみたけどそれっぽいのが見つからなかったので…

2020-03-15 08:13 UTC, hosakou commented
@SofPyon 

修正しました！

作成から3日以内かどうか判断する関数だけ1つにまとめました！

2020-03-15 10:07 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！

メモ）
isNew() のテストコード書きたい

2020-03-15 10:08 UTC, merged